module.exports = {
	handleStartCommand: require('./handle-start-command'),
	handleStopCommand: require('./handle-stop-command'),
	handleFAQCommand: require('./handle-faq-command'),
	handleVersionCommand: require('./handle-version-command'),
	handleTeamRatingsCommand: require('./handle-team-ratings-command'),
	handleSplitVariantButtonClick: require('./handle-split-variant-button-click'),
	handleTeamsQuantityButtonClick: require('./handle-teams-quantity-button-click'),
	handleText: require('./handle-text'),
	handleRandomCaptainsButtonClick: require('./handle-random-captains-button-click'),
	handleRemainCaptainsSelectionOrderButtonClick: require('./handle-remain-captains-selection-order-button-click'),
	handleRandomCaptainsSelectionOrderButtonClick: require('./handle-random-captains-selection-order-button-click'),
	handleCancelLastChoiceButtonClick: require('./handle-cancel-last-choice-button-click'),
	handleChangeSequenceButtonClick: require('./handle-change-sequence-button-click'),
	handleChangeCaptainsButtonClick: require('./handle-change-captains-button-click'),
	handlePlayerButtonClick: require('./handle-player-button-click'),
	handleTransfersButtonClick: require('./handle-transfers-button-click'),
	handleFinishTransfersButtonClick: require('./handle-finish-transfers-button-click'),
	handleError: require('./handle-error'),
}
